---
- hosts: servers
  become: yes
  tasks:
    - name: Install dependencies for Watchman
      apt:
        name: 
          - autoconf
          - automake
          - build-essential
          - python-dev
          - libtool
          - libssl-dev
          - pkg-config
        state: present

    - name: Clone Watchman repository
      git:
        repo: 'https://github.com/facebook/watchman.git'
        dest: /opt/watchman

    - name: Install Watchman
      shell: |
        cd /opt/watchman
        git checkout v2022.06.06.00
        ./autogen.sh
        ./configure
        make
        make install
